package org.openmrs.module.kenyaimmunisationplatform.metadata;

import org.openmrs.PatientIdentifierType.LocationBehavior;
import org.openmrs.module.idgen.validator.LuhnMod25IdentifierValidator;
import org.openmrs.module.metadatadeploy.bundle.AbstractMetadataBundle;
import org.springframework.stereotype.Component;

import static org.openmrs.module.metadatadeploy.bundle.CoreConstructors.encounterType;
import static org.openmrs.module.metadatadeploy.bundle.CoreConstructors.form;
import static org.openmrs.module.metadatadeploy.bundle.CoreConstructors.patientIdentifierType;

/**
 * Created by amosl on 3/6/17.
 */
@Component
public class CommonMetadata extends AbstractMetadataBundle {
	
	public static final class _EncounterType {
		
		public static final String REGISTRATION = "8a3d7e03-0250-11e7-aef1-54271eac1477";
		
		public static final String TRIAGE = "991b7123-0250-11e7-aef1-54271eac1477";
		
		public static final String VACCINATION = "b5a54d86-0250-11e7-aef1-54271eac1477";
	}
	
	public static final class _Form {
		
		public static final String CHILD_ENROLLMENT = "5295b23d-024f-11e7-aef1-54271eac1477";
		
		public static final String TRIAGE = "6985afe3-024f-11e7-aef1-54271eac1477";
		
		public static final String BCG = "7732c7c5-024f-11e7-aef1-54271eac1477";
		
		public static final String VITAMIN_A = "967647cc-024f-11e7-aef1-54271eac1477";
		
		public static final String VACCINATION = "4c272b32-025c-11e7-aef1-54271eac1477";
	}
	
	public static final class _PatientIdentifierType {
		
		public static final String OPENMRS_ID = "7bd003df-030c-11e7-b443-54271eac1477";
		
		public static final String CWC_NUMBER = "893bcc12-030c-11e7-b443-54271eac1477";
		
		public static final String DISTRICT_REGISTRATION_NUMBER = "bffa3601-030c-11e7-b443-54271eac1477";
		
		public static final String NATIONAL_ID = "ccd8e564-030c-11e7-b443-54271eac1477";
		
		public static final String NATIONAL_UNIQUE_PATIENT_IDENTIFIER = "dae8f6b8-030c-11e7-b443-54271eac1477";
		
		public static final String OLD_ID = "e6b5c3b5-030c-11e7-b443-54271eac1477";
		
		public static final String HDSS_NUMBER = "fc1c83d1-030c-11e7-b443-54271eac1477";
		
		public static final String PATIENT_CLINIC_NUMBER = "04222d69-030d-11e7-b443-54271eac1477";
		
		public static final String PERMANENT_REGISTER_NUMBER = "1b12fc38-030d-11e7-b443-54271eac1477";
	}
	
	@Override
	public void install() {
		
		install(encounterType("Registration", "Initial data collection for a patient, not specific to any program",
		    _EncounterType.REGISTRATION));
		install(encounterType("Triage", "Collection of limited data prior to a more thorough examination",
		    _EncounterType.TRIAGE));
		install(encounterType("Vaccination", "Collection of information on vaccination given", _EncounterType.VACCINATION));
		
		install(form("Child Enrollment Form", "The first form that captures basic demographic information on the "
		        + "child and caregiver information", _EncounterType.REGISTRATION, "1", _Form.CHILD_ENROLLMENT));
		install(form("Triage", "This form is the first form filled when a KNOWN patient enters the clinic",
		    _EncounterType.TRIAGE, "1", _Form.TRIAGE));
		install(form("BCG", "This form collects the BCG information", _EncounterType.VACCINATION, "1", _Form.BCG));
		install(form("Vitamin A", "This form collects information on the vitamin A distribution to the child",
		    _EncounterType.VACCINATION, "1", _Form.VITAMIN_A));
		install(form("Vaccination", "This form collects the information on the vaccination that is given.",
		    _EncounterType.VACCINATION, "1", _Form.VACCINATION));
		
		install(patientIdentifierType("OpenMRS ID", "Medical Record Number generated by OpenMRS for every patient", null,
		    null, LuhnMod25IdentifierValidator.class, LocationBehavior.REQUIRED, true, _PatientIdentifierType.OPENMRS_ID));
		install(patientIdentifierType("CWC Number", "Assigned to a child patient when enrolling into the Child "
		        + "Welfare Clinic (CWC)", ".{1,14}",
		    "Should take the format (CWC-MFL code-serial number) e.g CWC-15007-00001", null, LocationBehavior.NOT_USED,
		    true, _PatientIdentifierType.CWC_NUMBER));
		install(patientIdentifierType("District Registration Number", "Assigned to every TB patient", null, null, null,
		    LocationBehavior.NOT_USED, false, _PatientIdentifierType.DISTRICT_REGISTRATION_NUMBER));
		install(patientIdentifierType("National ID", "Kenyan national identity card number", "\\d{5,10}",
		    "Between 5 and 10 consecutive digits", null, LocationBehavior.NOT_USED, false,
		    _PatientIdentifierType.NATIONAL_ID));
		install(patientIdentifierType("National Unique patient identifier", "National Unique patient identifier", ".{1,14}",
		    "At most 14 characters long", null, LocationBehavior.NOT_USED, false,
		    _PatientIdentifierType.NATIONAL_UNIQUE_PATIENT_IDENTIFIER));
		install(patientIdentifierType("Old Identification Number", "Identifier given out prior to OpenMRS", null, null,
		    null, LocationBehavior.NOT_USED, false, _PatientIdentifierType.OLD_ID));
		install(patientIdentifierType("HDSS Number", "Unique number for HDSS integration", null, null, null,
		    LocationBehavior.NOT_USED, false, _PatientIdentifierType.HDSS_NUMBER));
		install(patientIdentifierType("Patient Clinic Number", "Assigned to the patient at a clinic service (not "
		        + "globally unique)", ".{1,15}", "At most 15 characters long", null, LocationBehavior.NOT_USED, false,
		    _PatientIdentifierType.PATIENT_CLINIC_NUMBER));
		install(patientIdentifierType("Permanent Register Number", "Assigned to a patient upon first entry to the "
		        + "permanent register", ".{1,14}", "Accepts alphanumeric values only", null, LocationBehavior.NOT_USED,
		    false, _PatientIdentifierType.PERMANENT_REGISTER_NUMBER));
		
	}
}
